### PR TITLE
Re-import and update of Eigen patches for CUDA

### PR DESCRIPTION
**Pull request by ericcano**
When moving CMSSW from running against cms/master/d812f411c3f9 to this branch, some CUDA fixes were lost. This leads to compilation issues as described in https://github.com/cms-sw/cmssw/issues/33797

This PR re-imports and adapt the modifications in branch cms/master/d812f411c3f9 release and fixes this issue.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by ericcano** [comment]
I missed some conflicts in areas not used by the PixelTrackFitting module. Eigen was now tested with its own system tests. 

One test fails, but failed already previously in this branch:
```
$  ../cmake-3.20.3-linux-x86_64/bin/ctest --rerun-failed --output-on-failure
Test project /data/user/cano/Eigen-investigation/eigen_tests
    Start 876: sparse_extra_3
1/1 Test #876: sparse_extra_3 ...................Subprocess aborted***Exception:   0.11 sec
Initializing random number generator with seed 1622542244
Repeating each test 10 times
nb_temporaries == 3
Test (sparse_product<DynamicSparseMatrix<float, ColMajor> >()) failed in /data/user/cano/eigen/unsupported/test/../../test/sparse_product.cpp (106)
    ("m4 = m2*m3") && nb_temporaries==2
Stack:
  - (sparse_product<DynamicSparseMatrix<float, ColMajor> >())
  - sparse_extra
  - Seed: 1622542244



0% tests passed, 1 tests failed out of 1

Label Time Summary:
Unsupported    =   0.11 sec*proc (1 test)

Total Test time (real) =   0.15 sec

The following tests FAILED:
        876 - sparse_extra_3 (Subprocess aborted)
Errors while running CTest
```

**Comment by ericcano** [comment]
The failed unit test link in Jenkins now reports a success (```Started by Naginator after the failure of build PR cms-externals/eigen-git-mirror#4 slc7_amd64_gcc900 (now deleted)```). Should we wake @cmsbuild up somehow?

**Comment by mrodozov** [comment]
ah I didn't reply, well I did but github had some trouble earlier
yes this test fails in the IB , the test is fine
I wanted to ask if as the title says - did this changes already has been in and then missed to be put on top ... ?
otherwise it's good, we can even test the failing test if you like

**Comment by ericcano** [comment]
Yes, the changes used to be in.

The re-imported changes (that I had to adapt) are in the `cms/master/d812f411c3f9` branch, which was the production as `/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/eigen/d812f411c3f9-ghbfee`  from `CMSSW_11_2_0` until `CMSSW_11_3_0_pre4`, before we switched to the current version `/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/eigen/011e0db31d1bed8b7f73662be6d57d9f30fa457a` on `CMSSW_11_3_0_pre5`.
(See the output of: `grep \"EIGEN_BASE\"  /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/*/config/toolbox/slc7_amd64_gcc900/tools/selected/eigen.xml`).

The re-import is a cherry-pick of the last commits (d812f41..b20a61c) on top of the current production branch (`cms/master/011e0db31d1bed8b7f73662be6d57d9f30fa457a`), plus few extra modifications.

**Comment by mrodozov** [comment]
lets try it also for arm and ppc and then we get it in

**Pull request merged**
