### PR TITLE
Revert "fix for vec_cmpne of power9"

### PR DESCRIPTION
**Pull request by fwyzard**
This reverts commit 4ad2a6cf17758d5a249fa78829810233222c8294.

Should no longer be needed with GCC 8 and later.

### CODE REVIEW

**Comment by fwyzard** [comment]
@smuzaffar how do we test this with CMSSW on Power ?

**Comment by smuzaffar** [comment]
please test for CMSSW_12_1_X/slc7_ppc64le_gcc9
@fwyzard , this should start the test for power

**Comment by fwyzard** [comment]
Ah, nice.
So we don't need to make an updated version of the external in cmsdist beforehand ?

**Comment by smuzaffar** [comment]
no we do not need cmsdist update. `bot` uses `cmsBuild --source toolname=local-src-dir` feature and override the sources.  Once successfully tested here then we can merge and open cmsdist PR to include latest commit.

**Comment by fwyzard** [comment]
While it looks like gcc should be happy, `genreflex` is not, because its header defines `vec_cmpne` only if `__POWER9_VECTOR__` is defined - and while I can work around that by explicitly defining it, this breaks the following compilation - probably because we actually target Power 8, not Power 9.

Since they are not really Eigen specific, we *could* move the definitions somewhere else - or just don't touch anything for the time being :-)

**Pull request closed without merging**
