### PR TITLE
More Eigen GPU work, with fix for CUDA 11.4

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test for CMSSW_12_1_X/slc7_amd64_gcc11

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test for CMSSW_12_1_X/slc7_amd64_gcc11

**Comment by fwyzard** [comment]
> -1
> 
> **Failed Tests**: Build
> **Summary**: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ddb31b/17843/summary.html
> **COMMIT**: [2916568](https://github.com/cms-externals/eigen-git-mirror/commit/29165681f5c18f83b0dd7decb63c98dd84efbe98)
> **CMSSW**: CMSSW_12_1_X_2021-08-16-1100/slc7_amd64_gcc11
> **User test area**: For local testing, you can use `/cvmfs/cms-ci.cern.ch/week0/cms-externals/eigen-git-mirror/7/17843/install.sh` to create a dev area with all the needed externals and cmssw changes.
> ## Build
> 
> I found compilation error when building:
> 
> >> Cuda Device Link tmp/slc7_amd64_gcc11/src/HeterogeneousCore/CUDAUtilities/test/gpuPrefixScan_t/gpuPrefixScan_t_cudadlink.o 
> >> Building binary gpuPrefixScan_t
> Copying tmp/slc7_amd64_gcc11/src/HeterogeneousCore/CUDAUtilities/test/gpuPrefixScan_t/gpuPrefixScan_t to productstore area:
> >> Compiling  /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-16-1100/src/HeterogeneousCore/CUDAUtilities/test/radixSort_t.cu
> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-16-1100/src/HeterogeneousCore/CUDAUtilities/test/radixSort_t.cu: In function 'void go(bool) [with T = float; int NS = 2; U = float; LL = double]':
> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-16-1100/src/HeterogeneousCore/CUDAUtilities/test/radixSort_t.cu:145:15: error: array subscript 'long unsigned int[0]' is partly outside array bounds of 'float [1]' [-Werror=array-bounds]
>   145 |           *k = (*k >> sh) << sh;
>       |           ~~~~^~~~~~~~
> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-08-16-1100/src/HeterogeneousCore/CUDAUtilities/test/radixSort_t.cu:139:6: note: while referencing 'k1'
>   139 |         auto k1 = a[ind[j]];
>       |      ^

Looks like https://github.com/cms-sw/cmssw/issues/34918 is fixed.

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw#34929 for CMSSW_12_1_X/slc7_amd64_gcc11

**Comment by fwyzard** [comment]
Looks like cms-sw/cmssw#34918 and cms-sw/cmssw#34917 are both fixed.

**Comment by smuzaffar** [comment]
please test
lets retest based on newer IB ( do not know why there are too many comparison diffs)

**Comment by smuzaffar** [comment]
+externals
looks good to go

**Pull request merged**
